- name: Deploy Application to Kubernetes
  hosts: localhost
  tasks:
    - name: Debug file path
      command: ls -l /var/lib/jenkins/deployment.yaml
      register: result

    - name: Show debug info
      debug:
        msg: "{{ result.stdout }}"

    - name: Check if kubectl is installed
      command: which kubectl
      register: kubectl_check
      ignore_errors: yes

    - name: Fail if kubectl is not installed
      fail:
        msg: "kubectl is not installed or not in the PATH!"
      when: kubectl_check.failed

    - name: Apply Kubernetes Deployment
      command: kubectl apply -f /var/lib/jenkins/deployment.yaml
      register: apply_result
      ignore_errors: yes

    - name: Debug kubectl apply result
      debug:
        msg: "{{ apply_result.stdout }}"
      when: apply_result.stdout is defined

    - name: Fail if kubectl apply failed
      fail:
        msg: "kubectl apply failed!"
      when: apply_result.failed

