- hosts: all
  become: yes
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Kubernetes tools
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - kubectl
        - kubelet
        - kubeadm

    - name: Start Kubernetes services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - kubelet
        - docker

